### ISSUE TITLE
MySQL Errors?

### ISSUE THREAD

**Issue by hlaplante** [Crimsonfoxy/Statistician-v2#4]
Hello, i'm getting these errors (this is a fresh copy of Statistician v2.0.12)

```
2012-08-21 21:31:14 [INFO] [Statistician] Enabling Statistician v2.0.12
2012-08-21 21:31:15 [INFO] [Statistician] Could not find a database version, creating one from scratch.
2012-08-21 21:31:15 [INFO] [Statistician] Patching database from v0 to v10.
2012-08-21 21:31:34 [SEVERE] [Statistician] Critical Error, could not connect to mySQL. Is the database Available? Check config file and try again. (An error occured while executing the database patch v1.)
2012-08-21 21:31:34 [SEVERE] An error occured while executing the database patch v1.
2012-08-21 21:31:34 [SEVERE]    at com.ChaseHQ.Statistician.Database.Database.patchDB(Database.java:193)
2012-08-21 21:31:34 [SEVERE]    at com.ChaseHQ.Statistician.Database.Database.<init>(Database.java:29)
2012-08-21 21:31:34 [SEVERE]    at com.ChaseHQ.Statistician.StatisticianPlugin.onEnable(StatisticianPlugin.java:51)
2012-08-21 21:31:34 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
2012-08-21 21:31:34 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:365)
2012-08-21 21:31:34 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
2012-08-21 21:31:34 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:265)
2012-08-21 21:31:34 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:247)
2012-08-21 21:31:34 [SEVERE]    at net.minecraft.server.MinecraftServer.i(MinecraftServer.java:296)
2012-08-21 21:31:34 [SEVERE]    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:275)
2012-08-21 21:31:34 [SEVERE]    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:225)
2012-08-21 21:31:34 [SEVERE]    at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:140)
2012-08-21 21:31:34 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:378)
2012-08-21 21:31:34 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
2012-08-21 21:31:34 [SEVERE] Caused by: com.ChaseHQ.Statistician.Database.RuntimeSqlException: Error executing: DROP PROCEDURE IF EXISTS `incrementBlockDestroy`
.  Cause: java.sql.SQLException: Column count of mysql.proc is wrong. Expected 20, found 16. The table is probably corrupted
2012-08-21 21:31:34 [SEVERE]    at com.ChaseHQ.Statistician.Database.ScriptRunner.executeLineByLine(ScriptRunner.java:136)
2012-08-21 21:31:34 [SEVERE]    at com.ChaseHQ.Statistician.Database.ScriptRunner.runScript(ScriptRunner.java:98)
2012-08-21 21:31:34 [SEVERE]    at com.ChaseHQ.Statistician.Database.Database.patchDB(Database.java:191)
2012-08-21 21:31:34 [SEVERE]    ... 13 more
2012-08-21 21:31:34 [SEVERE] Caused by: java.sql.SQLException: Column count of mysql.proc is wrong. Expected 20, found 16. The table is probably corrupted
2012-08-21 21:31:35 [SEVERE]    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
2012-08-21 21:31:35 [SEVERE]    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
2012-08-21 21:31:35 [SEVERE]    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
2012-08-21 21:31:35 [SEVERE]    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
2012-08-21 21:31:35 [SEVERE]    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
2012-08-21 21:31:35 [SEVERE]    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
2012-08-21 21:31:35 [SEVERE]    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570)
2012-08-21 21:31:35 [SEVERE]    at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:779)
2012-08-21 21:31:35 [SEVERE]    at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:622)
2012-08-21 21:31:35 [SEVERE]    at com.ChaseHQ.Statistician.Database.ScriptRunner.executeStatement(ScriptRunner.java:217)
2012-08-21 21:31:35 [SEVERE]    at com.ChaseHQ.Statistician.Database.ScriptRunner.handleLine(ScriptRunner.java:192)
2012-08-21 21:31:35 [SEVERE]    at com.ChaseHQ.Statistician.Database.ScriptRunner.executeLineByLine(ScriptRunner.java:129)
2012-08-21 21:31:35 [SEVERE]    ... 15 more
2012-08-21 21:31:35 [INFO] [Statistician] Disabling Statistician v2.0.12
```

**Comment by hlaplante** [comment]
shit i fail, forget about this, i needed to upgrade my mysql DB
